AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/CaseIndentation:
  IndentWhenRelativeTo: end

Style/AsciiComments:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
      inject: 'inject'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*_spec.rb

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Lint/EndAlignment:
  AlignWith: variable

Style/FormatString:
  Enabled: false

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/WordArray:
  Enabled: false

Style/RedundantSelf:
  Enabled: false
